# -*- coding: utf-8 -*-
"""Consonante.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h70LricAE5ts9FViHWGfIzXu-zmQejsD
"""

# Objetivo: Conteo de Consonantes
# Nombre:   Cobeñas Blanco Victor Luis
# Fecha:    27/04/2025

while(True):
    menu =  int(input("""
    ====== BIENVENIDO A MI MENU ======
    1. CONTAR CONSONANTES SIN VOCALES
    2. SALIR
    """))
    if(menu == 1):
        while(True):
          palabra = input("Ingrese la palabra: ")
          break
          while(True):
              menu =  int(input("""f\
              2. SALIR
              """))
              if(menu == 2):
                print("Hasta Luego")