# -*- coding: utf-8 -*-
"""Masa Corporal.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10Ei9Dv1kNSyO7_76ODMq0aWcOwOEfzJ9
"""

# Objetivo: Calcular la masa corporal
# Apellido: Cobeñas Blanco, Victor Luis

# IMC
# IMC = PESO / TALLA

peso = float(input("Ingrese peso: "))
talla = float(input("Ingrese talla: "))
IMC = peso / talla
print("Su masa corporal es:",IMC)