# -*- coding: utf-8 -*-
"""Recursividad de Division.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UdBLlH8XsticrCKm6W6nLvStmg-h0OqF
"""

# RECURSIVIDAD APLICANDO DIVISION DE DOS NUMEROS
def FunRecurDiv(w,z):
  if(w==0 or z==0):
    return 0
  else:
    return( z + FunRecurDiv(w-z, z)) #Aplicamos la funcion

var_Div1 = int(input("Ingrese el pirmer Digito: "))     #Ingresamos el Primer digito
var_Div2 = int(input("Ingrese el segundo Digito: "))    #Ingresamos el segundo digito
FunRecurDiv(var_Div1, var_Div2)